---
title: "CodeBook"
---
<!DOCTYPE html>
<html>

This codebook summarizes the data fields found in tidy.txt

## Identifiers
Both of the following were added to the raw data and recoded as factor variables:

<ul>
<li> Subject-The label ID of the test subject 

<li> Activity-The activity being performed when the measurements were being taken 

##Activity Labels
The levels of the activity variable are labeled as follows: 

<ul>
<li> walking (value 1): Subject was walking during measurement

<li> walking_upstairs (value 2): Subject was walking up stairs during measurement

<li> walking_downstairs (value 3): Subject was walking down stairs during measurement 

<li> siting (value 4): Subject was sitting during measurement

<li> standing (value 5): Subject was standing during measurement

<li> laying (value 6): Subject was laying down during meaurement 

##Measurements
The following variables are numeric variables representing means and standard deviations filtered from the original 561 variables in the raw data

<ul>
<li> tBodyAccMeanX
<li> tBodyAccMeanY
<li>tBodyAccMeanZ
<li>tBodyAccStdX
<li>tBodyAccStdY
<li>tBodyAccStdZ
<li>tGravityAccMeanX
<li>tGravityAccMeanY
<li>tGravityAccMeanZ
<li>tGravityAccStdX
<li>tGravityAccStdY
<li>tGravityAccStdZ
<li>tBodyAccJerkMeanX
<li>tBodyAccJerkMeanY
<li>tBodyAccJerkMeanZ
<li>tBodyAccJerkStdX
<li>tBodyAccJerkStdY
<li>tBodyAccJerkStdZ
<li>tBodyGyroMeanX
<li>tBodyGyroMeanY
<li>tBodyGyroMeanZ
<li>tBodyGyroStdX
<li>tBodyGyroStdY
<li>tBodyGyroStdZ
<li>tBodyGyroJerkMeanX
<li>tBodyGyroJerkMeanY
<li>tBodyGyroJerkMeanZ
<li>tBodyGyroJerkStdX
<li>tBodyGyroJerkStdY
<li>tBodyGyroJerkStdZ
<li>tBodyAccMagMean
<li>tBodyAccMagStd
<li>tGravityAccMagMean
<li>tGravityAccMagStd
<li>tBodyAccJerkMagMean
<li>tBodyAccJerkMagStd
<li>tBodyGyroMagMean
<li>tBodyGyroMagStd
<li>tBodyGyroJerkMagMean
<li>tBodyGyroJerkMagStd
<li>fBodyAccMeanX
<li>fBodyAccMeanY
<li>fBodyAccMeanZ
<li>fBodyAccStdX
<li>fBodyAccStdY
<li>fBodyAccStdZ
<li>fBodyAccMeanFreqX
<li>fBodyAccMeanFreqY
<li>fBodyAccMeanFreqZ
<li>fBodyAccJerkMeanX
<li>fBodyAccJerkMeanY
<li>fBodyAccJerkMeanZ
<li>fBodyAccJerkStdX
<li>fBodyAccJerkStdY
<li>fBodyAccJerkStdZ
<li>fBodyAccJerkMeanFreqX
<li>fBodyAccJerkMeanFreqY
<li>fBodyAccJerkMeanFreqZ
<li>fBodyGyroMeanX
<li>fBodyGyroMeanY
<li>fBodyGyroMeanZ
<li>fBodyGyroStdX
<li>fBodyGyroStdY
<li>fBodyGyroStdZ
<li>fBodyGyroMeanFreqX
<li>fBodyGyroMeanFreqY
<li>fBodyGyroMeanFreqZ
<li>fBodyAccMagMean
<li>fBodyAccMagStd
<li>fBodyAccMagMeanFreq
<li>fBodyBodyAccJerkMagMean
<li>fBodyBodyAccJerkMagStd
<li>fBodyBodyAccJerkMagMeanFreq
<li>fBodyBodyGyroMagMean
<li>fBodyBodyGyroMagStd
<li>fBodyBodyGyroMagMeanFreq
<li>fBodyBodyGyroJerkMagMean
<li>fBodyBodyGyroJerkMagStd
<li>fBodyBodyGyroJerkMagMeanFreq



</html>